### ISSUE TITLE
Add C++ program to find greatest and the smallest among three  numbers using pointers (Hacktoberfest)

### ISSUE THREAD

**Issue by AB-san** [Vicky-Jha/Number-Theory#2]
Please assign me this issue so that I can Add C++ program to find greatest and the smallest among three  numbers using pointers 
Participant of Hacktoberfest 2021 :)

**Comment by uzzal623** [comment]
can u assign this to me ?

**Comment by uzzal623** [comment]
@Vicky-Jha thank you so much I have submitted my PR.

**Comment by Vicky-Jha** [comment]
@uzzal623  Your PR is approved, since this was your 1st PR, you need to submit 3 more PR's to win this challenge

**Comment by Pratixingh** [comment]
Could u please assign me this problem .  
Participant of Hacktoberfest 2021

**Comment by Gourav-s12** [comment]
can u assign this issue to me? and thank you
