### ISSUE TITLE
Add a Java program to rotate an array using the Juggling algorithm ( Hacktoberfest)

### ISSUE THREAD

**Issue by AB-san** [Vicky-Jha/Number-Theory#3]
Please assign me this issue so that I can add a Java program to rotate an array using the Juggling algorithm
Participant of Hacktoberfest 2021

**Comment by Gourav-s12** [comment]
can i get this issue ? i am a java programmer.

**Comment by Gourav-s12** [comment]
please review and marge it. thank you #15

**Comment by AB-san** [comment]
Kindly review my pr #26
