### ISSUE TITLE
Add some python basic programs for  list, string and tupes for Hacktoberfest

### ISSUE THREAD

**Issue by tjanhvi** [Vicky-Jha/Number-Theory#4]
Please assign me this issue.

Desrcription :-
I will make three indivisiual folders for the programs  of string, list, and tuple in python folder and add some programs into it

**Comment by tjanhvi** [comment]
Hello @Vicky-Jha  Can i know why there is a problem while forking the repo as 
![image](https://user-images.githubusercontent.com/78703730/135804968-041d4b53-65e2-4ae2-a894-7c316e22ca09.png)

**Comment by Vicky-Jha** [comment]
it was due to a file name, changes are made  now @tjanhvi  try again

**Comment by tjanhvi** [comment]
> it was due to a file name, changes are made now @tjanhvi try again

yes now fine :)
